/* StudyFlow — lógica de cada página (PAGES[nome] é chamado por main.js). */
'use strict';
const PAGES={},PR=['Baixa','Média','Alta','Urgente'],C=()=>$('#content');
const subOpts=()=>[['','—']].concat(DB.get('subjects').map(s=>[s.name])),pl={trial:'Teste grátis',premium:'Premium',cancelled:'Cancelada',admin:'Admin'};
const rev=()=>DB.get('users').filter(u=>u.plan==='premium').length*24;
function bars(l,v,u=''){const m=Math.max(...v,1);return `<div class="chart">${v.map((x,i)=>`<div class="cb"><em>${x}${u}</em><i style="height:${x/m*100}%"></i><small>${l[i]}</small></div>`).join('')}</div>`}
const months=()=>[...Array(6)].map((_,i)=>{const n=new Date(),e=new Date(n.getFullYear(),n.getMonth()-5+i+1,1);return{l:new Date(e-864e5).toLocaleDateString('pt-PT',{month:'short'}),e:e.toISOString(),s:new Date(e.getFullYear(),e.getMonth()-1,1).toISOString()}});
const priceCard=()=>`<div class="price card center"><small>Primeiro mês</small><div class="n">0 €</div><p>Experimenta todas as funcionalidades durante 30 dias.</p><hr style="border-color:var(--line)"><small>Depois — StudyFlow Premium</small><div class="n">24 € <small>/ mês</small></div><p>Continua a utilizar todas as ferramentas do StudyFlow.</p><a class="btn p" href="register.html">Começar gratuitamente</a><p><small>Sem compromisso. Podes cancelar a qualquer momento.</small></p></div>`;
/* ---------- Páginas públicas ---------- */
const FT=[['📅','Calendário escolar','Aulas, testes, trabalhos e eventos.'],['✅','Lista de tarefas','Cria e organiza tarefas escolares.'],['🚩','Prioridades','Baixa, média, alta ou urgente.'],['📚','Disciplinas','Organiza as tuas disciplinas.'],['🧭','Planos de estudo','Planos personalizados.'],['⏱️','Temporizador','Sessões ao estilo Pomodoro.'],['🏆','Objetivos','Metas académicas e pessoais.'],['📊','Progresso','Estatísticas e evolução.'],['🔔','Lembretes','Testes, tarefas e sessões.'],['🎯','Modo concentração','Só o essencial para estudar.']];
PAGES.index=()=>{C().innerHTML=`<section class="hero"><div class="wrap in"><p class="eyebrow">StudyFlow</p><h1>Organiza o teu tempo.<br><span class="gold">Domina os teus estudos.</span></h1><p class="lead">A tua plataforma completa para planear, estudar, acompanhar objetivos e transformar a tua produtividade.</p><div class="row mid"><a class="btn p" href="register.html">Criar conta</a><a class="btn" href="login.html">Entrar</a><a class="btn" href="pricing.html">Ver preços</a></div></div></section>
<section class="sec wrap center"><h2>Tudo o que precisas para <span class="gold">estudar melhor.</span></h2><div class="grid">${[['🗂️','Organização','Organiza aulas, tarefas, trabalhos e exames num único lugar.'],['⚡','Produtividade','Planeia o teu tempo e mantém o foco no que realmente importa.'],['📈','Progresso','Acompanha os teus objetivos e vê a tua evolução.'],['🎯','Foco','Reduz as distrações com ferramentas para sessões focadas.']].map(f=>`<div class="card"><div class="ic">${f[0]}</div><h3>${f[1]}</h3><p>${f[2]}</p></div>`).join('')}</div></section>
<section id="funcionalidades" class="sec wrap center"><h2>As tuas ferramentas. <span class="gold">Num só lugar.</span></h2><div class="grid">${FT.map(f=>`<div class="card"><div class="ic">${f[0]}</div><h3>${f[1]}</h3><p>${f[2]}</p></div>`).join('')}</div></section>
<section class="sec wrap center"><h2>Começa <span class="gold">gratuitamente.</span></h2>${priceCard()}</section>
<section class="sec center"><h2>O teu próximo nível <span class="gold">começa hoje.</span></h2><p class="mute">Organiza os teus estudos, define os teus objetivos e transforma o teu tempo em progresso.</p><a class="btn p" href="register.html">Começar gratuitamente</a></section>`};
PAGES.pricing=()=>{C().innerHTML=`<section class="sec wrap center"><h1>Preços <span class="gold">simples.</span></h1>${priceCard()}</section>`};
const text=(t,b)=>()=>{C().innerHTML=`<div class="prose"><h1 class="gold">${t}</h1>${b}</div>`};
PAGES.about=text('Sobre nós','<p>O StudyFlow nasceu para ajudar estudantes do 1.º ciclo ao ensino superior a organizar o tempo, criar bons hábitos e acompanhar o progresso académico.</p><p>Acreditamos que ferramentas simples e bonitas fazem a diferença.</p><a class="btn p" href="register.html">Criar conta</a>');
PAGES.terms=text('Termos e condições','<p>Protótipo de demonstração. Primeiro mês gratuito; depois 24 €/mês, cancelável a qualquer momento. Texto legal definitivo a preencher.</p>');
PAGES.privacy=text('Política de privacidade','<p>Nesta demonstração os dados ficam apenas no teu browser (localStorage). Texto legal definitivo a preencher.</p>');
PAGES.contact=()=>{C().innerHTML=`<div class="prose"><h1 class="gold">Contactos</h1><form id="cf" novalidate><label>Nome<input name="n"></label><label>E-mail<input name="e" type="email"></label><label>Mensagem<textarea name="m" rows="4"></textarea></label><p class="err" role="alert"></p><button class="btn p">Enviar</button></form></div>`;
$('#cf').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!d.n.trim()||!/^\S+@\S+\.\S+$/.test(d.e)||!d.m.trim()){$('.err').textContent='Preenche todos os campos com um e-mail válido.';return}
/* BACKEND: POST /api/contact */const m=DB.get('messages');m.push({...d,date:today()});DB.set('messages',m);e.target.reset();$('.err').textContent='';toast('Mensagem enviada. Obrigado!')}};
/* ---------- Autenticação ---------- */
const pwField=(id,l)=>`<label>${l}<div class="pw"><input id="${id}" type="password" autocomplete="${id==='pw'?'current-password':'new-password'}"><button type="button" class="btn sm" data-eye="${id}" aria-label="Mostrar/ocultar palavra-passe">👁</button></div></label>`;
const eyes=()=>$$('[data-eye]').forEach(b=>b.onclick=()=>{const i=$('#'+b.dataset.eye);i.type=i.type==='password'?'text':'password'});
const go=r=>{$('.err').className='err ok';$('.err').textContent=r.msg;setTimeout(()=>location.href=r.user.role==='admin'?'admin.html':'dashboard.html',700)};
PAGES.login=()=>{C().innerHTML=`<div class="card auth"><div class="logo gold center">StudyFlow</div><h2>Entrar</h2><form id="f" novalidate><label>E-mail<input id="em" type="email" autocomplete="email"></label>${pwField('pw','Palavra-passe')}<p class="err" role="alert"></p><button class="btn p" style="width:100%">Entrar</button></form><p><button class="lnk ok" id="fg">Esqueci-me da palavra-passe</button></p><p>Não tens conta? <a class="ok" href="register.html">Criar conta</a></p><small>Demo admin: admin@studyflow.pt / admin123</small></div>`;eyes();
$('#f').onsubmit=e=>{e.preventDefault();const r=loginUser($('#em').value,$('#pw').value);r.ok?go(r):$('.err').textContent=r.msg};
$('#fg').onclick=()=>openForm('Recuperar palavra-passe',[{n:'email',l:'E-mail',req:1},{n:'pw',l:'Nova palavra-passe',t:'password',req:1}],null,d=>{/* BACKEND: enviar e-mail com token de recuperação */
const us=DB.get('users'),u=us.find(x=>x.email===d.email.trim().toLowerCase());if(!u)return{err:'E-mail não encontrado.'};if(d.pw.length<6)return{err:'Mínimo 6 caracteres.'};u.pass=hash(d.pw);DB.set('users',us);toast('Palavra-passe redefinida (demo).')})};
PAGES.register=()=>{C().innerHTML=`<div class="card auth"><div class="logo gold center">StudyFlow</div><h2>Criar conta</h2><form id="f" novalidate><label>Nome<input id="nm" autocomplete="name"></label><label>E-mail<input id="em" type="email" autocomplete="email"></label>${pwField('pw','Palavra-passe')}${pwField('p2','Confirmar palavra-passe')}<p class="err" role="alert"></p><button class="btn p" style="width:100%">Criar conta</button></form><p>Já tens uma conta? <a class="ok" href="login.html">Entrar</a></p></div>`;eyes();
$('#f').onsubmit=e=>{e.preventDefault();const r=registerUser($('#nm').value,$('#em').value,$('#pw').value,$('#p2').value);r.ok?go(r):$('.err').textContent=r.msg}};
/* ---------- Dashboard ---------- */
PAGES.dashboard=()=>{const t=DB.get('tasks'),s=DB.get('studySessions'),h=new Date().getHours(),g=h<12?'Bom dia':h<20?'Boa tarde':'Boa noite',goal=DB.get('settings',{}).goalH||10,wk=hrs(s.filter(x=>x.date>=ago(6))),pct=Math.min(100,Math.round(wk/goal*100)),
td=t.filter(x=>!x.done&&(!x.due||x.due<=today())),up=[...DB.get('events').map(e=>({...e,k:'Evento'})),...DB.get('reminders').filter(r=>!r.done).map(r=>({title:r.title,date:r.date,time:r.time,k:r.type}))].filter(e=>e.date>=today()).sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||''))).slice(0,5);
C().innerHTML=`<h1>${g}, <span class="gold">${esc(me().name.split(' ')[0])}</span>!</h1><p class="mute">Vamos tornar o teu dia produtivo.</p><div class="stats">${st(t.filter(x=>!x.done).length,'Tarefas pendentes')+st(t.filter(x=>x.done).length,'Tarefas concluídas')+st(hrs(s)+' h','Horas estudadas')+st(pct+'%','Progresso semanal')}</div>
<div class="card" style="margin-bottom:16px"><small>Meta semanal: ${wk} / ${goal} h</small>${bar(pct)}</div><div class="two"><div class="card"><h3>Próximos eventos</h3>${up.map(e=>`<p><b>${esc(e.title)}</b> <span class="badge">${esc(e.k)}</span><br><small>${fd(e.date)} ${e.time||''}</small></p>`).join('')||'<p>Sem eventos. <a class="ok" href="calendar.html">Adicionar</a></p>'}</div>
<div class="card"><h3>Tarefas de hoje</h3>${td.map(x=>`<label><input type="checkbox" data-t="${x.id}">${esc(x.title)}</label>`).join('')||'<p>Nada para hoje. <a class="ok" href="tasks.html">Ver tarefas</a></p>'}</div></div>`;
$$('[data-t]').forEach(c=>c.onchange=()=>{const a=DB.get('tasks');a.find(x=>x.id===c.dataset.t).done=true;DB.set('tasks',a);PAGES.dashboard()})};
/* ---------- Tarefas, disciplinas, planos, objetivos, lembretes ---------- */
PAGES.tasks=()=>crud({key:'tasks',title:'Tarefas',newLabel:'Nova tarefa',toggle:'done',fields:[{n:'title',l:'Título',req:1},{n:'subject',l:'Disciplina',t:'select',opts:subOpts},{n:'priority',l:'Prioridade',t:'select',opts:PR,def:'Média'},{n:'due',l:'Prazo',t:'date'}],
filters:[{n:'s',l:'Estado',o:[['','Todas'],['p','Pendentes'],['c','Concluídas']]},{n:'p',l:'Prioridade',o:[['','Qualquer prioridade'],...PR.map(p=>[p,p])]}],filter:(i,q)=>(!q.s||(q.s==='c')===!!i.done)&&(!q.p||i.priority===q.p),
row:i=>`<b class="${i.done?'dn':''}">${esc(i.title)}</b> <span class="badge p${PR.indexOf(i.priority)}">${i.priority}</span><br><small>${esc(i.subject||'Sem disciplina')}${i.due?' · Prazo '+fd(i.due):''}</small>`});
PAGES.subjects=()=>crud({key:'subjects',title:'Disciplinas',newLabel:'Nova disciplina',fields:[{n:'name',l:'Nome',req:1},{n:'teacher',l:'Professor'},{n:'color',l:'Cor',t:'color',def:'#D4AF37'}],
row:s=>{const t=DB.get('tasks').filter(x=>x.subject===s.name),p=t.length?Math.round(t.filter(x=>x.done).length/t.length*100):0;return `<b><span class="dot" style="background:${esc(s.color)}"></span>${esc(s.name)}</b><br><small>${esc(s.teacher||'—')} · ${t.length} tarefas · ${p}%</small>${bar(p)}`}});
PAGES['study-plans']=()=>crud({key:'studyPlans',title:'Planos de estudo',newLabel:'Novo plano',toggle:'done',fields:[{n:'name',l:'Nome',req:1},{n:'subject',l:'Disciplina',t:'select',opts:subOpts},{n:'goal',l:'Objetivo'},{n:'start',l:'Início',t:'date',req:1},{n:'end',l:'Fim',t:'date',req:1},{n:'time',l:'Horário',t:'time'},{n:'sessions',l:'Nº de sessões',t:'number',min:1,def:5}],
validate:d=>d.end<d.start?'A data de fim tem de ser depois do início.':'',row:p=>`<b class="${p.done?'dn':''}">${esc(p.name)}</b> <span class="badge">${p.done?'Concluído':'Em curso'}</span><br><small>${esc(p.subject||'—')} · ${esc(p.goal||'')} · ${fd(p.start)}–${fd(p.end)} ${p.time||''} · ${p.sessions} sessões</small>`});
PAGES.goals=()=>crud({key:'goals',title:'Objetivos',newLabel:'Novo objetivo',fields:[{n:'title',l:'Objetivo (ex.: Estudar 10 horas esta semana)',req:1},{n:'target',l:'Meta',t:'number',min:1,def:10},{n:'current',l:'Progresso atual',t:'number',min:0,def:0},{n:'unit',l:'Unidade',def:'horas'},{n:'deadline',l:'Prazo',t:'date'}],
row:g=>{const p=Math.min(100,Math.round(g.current/(g.target||1)*100));return `<b>${esc(g.title)}</b> <span class="badge">${p}%</span><br><small>${g.current}/${g.target} ${esc(g.unit)}${g.deadline?' · Prazo '+fd(g.deadline):''}</small>${bar(p)}`},
extra:()=>'<button class="btn sm" data-a="inc">+1</button>',act:(a,i,all,draw)=>{i.current++;DB.set('goals',all);draw()}});
PAGES.reminders=()=>crud({key:'reminders',title:'Lembretes',newLabel:'Novo lembrete',toggle:'done',fields:[{n:'title',l:'Título',req:1},{n:'type',l:'Tipo',t:'select',opts:['Teste','Trabalho','Tarefa','Sessão de estudo']},{n:'date',l:'Data',t:'date',req:1},{n:'time',l:'Hora',t:'time'}],
row:r=>`<b class="${r.done?'dn':''}">${esc(r.title)}</b> <span class="badge">${esc(r.type)}</span><br><small>${fd(r.date)} ${r.time||''}</small>`});
/* ---------- Calendário ---------- */
PAGES.calendar=()=>{let d=new Date();d.setDate(1);const F=[{n:'title',l:'Título',req:1},{n:'subject',l:'Disciplina',t:'select',opts:subOpts},{n:'date',l:'Data',t:'date',req:1},{n:'time',l:'Hora',t:'time'}];
const form=i=>openForm(i&&i.id?'Editar evento':'Novo evento',F,i,v=>{const a=DB.get('events');if(i&&i.id)Object.assign(a.find(x=>x.id===i.id),v);else a.push({id:uid(),...v});DB.set('events',a);draw();toast('Guardado!')});
function draw(){const ev=DB.get('events'),y=d.getFullYear(),m=d.getMonth(),f=(new Date(y,m,1).getDay()+6)%7,n=new Date(y,m+1,0).getDate(),pre=`${y}-${String(m+1).padStart(2,'0')}-`,k=x=>pre+String(x).padStart(2,'0');let c='<div class="cd e"></div>'.repeat(f);
for(let x=1;x<=n;x++){const e=ev.filter(z=>z.date===k(x));c+=`<button class="cd ${k(x)===today()?'td':''}" data-d="${k(x)}" aria-label="Dia ${x}"><b>${x}</b>${e.slice(0,2).map(z=>`<small>${esc(z.title)}</small>`).join('')}${e.length>2?`<small>+${e.length-2}</small>`:''}</button>`}
const L=ev.filter(e=>e.date.startsWith(pre)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
C().innerHTML=`<div class="ph"><h1>Calendário</h1><button class="btn p" id="ne">+ Novo evento</button></div><div class="row mid"><button class="btn sm" id="pv" aria-label="Mês anterior">‹</button><h2>${d.toLocaleDateString('pt-PT',{month:'long',year:'numeric'})}</h2><button class="btn sm" id="nx" aria-label="Mês seguinte">›</button></div>
<div class="cal">${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(x=>`<div class="ch">${x}</div>`).join('')}${c}</div><h3>Eventos do mês</h3><div class="list" id="ls">${L.map(e=>`<div class="item" data-id="${e.id}"><div class="ib"><b>${esc(e.title)}</b><br><small>${fd(e.date)} ${e.time||''} · ${esc(e.subject||'—')}</small></div><div class="ia"><button class="btn sm" data-a="edit" aria-label="Editar">✎</button><button class="btn sm d" data-a="del" aria-label="Apagar">🗑</button></div></div>`).join('')||'<p class="mute">Sem eventos neste mês.</p>'}</div>`;
$('#pv').onclick=()=>{d.setMonth(m-1);draw()};$('#nx').onclick=()=>{d.setMonth(m+1);draw()};$('#ne').onclick=()=>form({date:today()});$$('.cd[data-d]').forEach(b=>b.onclick=()=>form({date:b.dataset.d}));
$('#ls').onclick=e=>{const b=e.target.closest('[data-a]');if(!b)return;const id=b.closest('[data-id]').dataset.id,a=DB.get('events');if(b.dataset.a==='edit')form(a.find(x=>x.id===id));else if(confirm('Apagar este evento?')){DB.set('events',a.filter(x=>x.id!==id));draw()}}}draw()};
/* ---------- Temporizador e modo concentração ---------- */
let ac,src;const noise=on=>{if(!on){src&&src.stop();src=null;return}ac=ac||new AudioContext();const b=ac.createBuffer(1,ac.sampleRate*2,ac.sampleRate),a=b.getChannelData(0);let l=0;for(let i=0;i<a.length;i++){l=(l+.02*(Math.random()*2-1))/1.02;a[i]=l*3.5}src=ac.createBufferSource();src.buffer=b;src.loop=true;const g=ac.createGain();g.gain.value=.4;src.connect(g).connect(ac.destination);src.start()};
function timer(focus){const M=[['Foco',25],['Pausa curta',5],['Pausa longa',15]],f=t=>String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');let mode=0,tot=1500,left=1500,iv=null,end=0,cust=false;
C().innerHTML=`<div class="ph"><h1>${focus?'Modo concentração':'Temporizador'}</h1></div><div class="card tc"><div class="row mid">${M.map((m,i)=>`<button class="btn sm" data-m="${i}">${m[0]} ${m[1]}′</button>`).join('')}</div><label>Minutos personalizados<div class="row"><input id="cu" type="number" min="1" max="180" value="25"><button class="btn sm" id="cs">Definir</button></div></label>
<div class="big" id="td">25:00</div>${bar(0).replace('<i ','<i id="tb" ')}<div class="row mid" style="margin-top:16px"><button class="btn p" id="go">Iniciar</button><button class="btn" id="rs">Reiniciar</button>${focus?'<button class="btn d" id="fin">Terminar sessão</button>':''}</div>
${focus?`<label>Objetivo atual<select id="fg"><option value="">—</option>${DB.get('goals').map(g=>`<option>${esc(g.title)}</option>`).join('')}</select></label><label><input type="checkbox" id="snd">Som ambiente (ruído suave)</label>`:''}</div><p class="center mute" id="hh"></p>`;
const hh=()=>$('#hh').textContent='Estudado hoje: '+hrs(DB.get('studySessions').filter(s=>s.date===today()))+' h',log=m=>{if(m<1)return;const s=DB.get('studySessions');s.push({id:uid(),date:today(),min:m});DB.set('studySessions',s);hh()},
show=()=>{$('#td').textContent=f(left);$('#tb').style.width=(100-left/tot*100)+'%';document.title=f(left)+' · StudyFlow'},
stop=()=>{clearInterval(iv);iv=null;document.body.classList.remove('focusing');$('#go').textContent=left<tot?'Retomar':'Iniciar'},
set=m=>{stop();tot=left=m*60;show();$('#go').textContent='Iniciar'},
fin=()=>{stop();const w=mode===0||cust;if(w)log(Math.round(tot/60));left=tot;show();toast('Sessão concluída! 🎉');modal(`<h2 class="gold">Sessão concluída 🎉</h2><p>${w?'Sessão registada nas tuas estatísticas.':'Pausa terminada. Pronto para continuar?'}</p><button class="btn p" data-c>OK</button>`)};
$$('[data-m]').forEach(b=>b.onclick=()=>{mode=+b.dataset.m;cust=false;set(M[mode][1])});$('#cs').onclick=()=>{const v=Math.min(180,Math.max(1,+$('#cu').value||25));cust=true;set(v)};
$('#go').onclick=()=>{if(iv){stop();return}end=Date.now()+left*1000;$('#go').textContent='Pausar';if(focus)document.body.classList.add('focusing');iv=setInterval(()=>{left=Math.max(0,Math.round((end-Date.now())/1000));show();if(!left)fin()},400)};
$('#rs').onclick=()=>set(tot/60);if(focus){$('#fin').onclick=()=>{const el=Math.floor((tot-left)/60);stop();if(mode===0||cust)log(el);set(tot/60);toast(el?'Sessão terminada e registada.':'Sessão terminada.')};$('#snd').onchange=e=>noise(e.target.checked)}hh()}
PAGES.timer=()=>timer(false);PAGES.focus=()=>timer(true);
/* ---------- Progresso ---------- */
PAGES.progress=()=>{const s=DB.get('studySessions'),t=DB.get('tasks'),g=DB.get('goals'),days=[...Array(7)].map((_,i)=>new Date(Date.now()-(6-i)*864e5)),pd=days.map(d=>hrs(s.filter(x=>x.date===d.toISOString().slice(0,10)))),M=months(),pm=M.map(m=>hrs(s.filter(x=>x.date>=m.s.slice(0,10)&&x.date<m.e.slice(0,10))));
C().innerHTML=`<div class="ph"><h1>Progresso</h1></div><div class="stats">${st(hrs(s)+' h','Horas estudadas')+st(t.filter(x=>x.done).length,'Tarefas concluídas')+st(s.length,'Sessões de estudo')+st(g.filter(x=>x.current>=x.target).length,'Objetivos concluídos')+st(hrs(s.filter(x=>x.date>=ago(6)))+' h','Esta semana')+st(pm[5]+' h','Este mês')}</div>
<div class="two"><div class="card"><h3>Progresso semanal (horas)</h3>${bars(days.map(d=>d.toLocaleDateString('pt-PT',{weekday:'short'})),pd)}</div><div class="card"><h3>Progresso mensal (horas)</h3>${bars(M.map(m=>m.l),pm)}</div></div>`};
/* ---------- Perfil e definições ---------- */
PAGES.profile=()=>{const u=me();C().innerHTML=`<div class="ph"><h1>Perfil</h1></div><div class="card"><div class="av">${esc(u.name[0].toUpperCase())}</div><h2>${esc(u.name)}</h2><p>${esc(u.email)}<br>Tipo de conta: <span class="badge">${pl[u.plan]}</span><br><small>Conta criada em ${fd(u.created.slice(0,10))}</small></p>
<div class="row"><button class="btn p" id="ed">Editar perfil</button>${u.plan==='premium'?'<button class="btn d" id="pm">Cancelar subscrição</button>':u.role==='admin'?'':'<button class="btn" id="pm">Passar a Premium (24 €/mês)</button>'}</div></div>`;
$('#ed').onclick=()=>openForm('Editar perfil',[{n:'name',l:'Nome',req:1},{n:'email',l:'E-mail',t:'email',req:1}],u,d=>{const us=DB.get('users');d.email=d.email.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(d.email))return{err:'E-mail inválido.'};if(us.some(x=>x.email===d.email&&x.id!==u.id))return{err:'E-mail já em uso.'};Object.assign(us.find(x=>x.id===u.id),d);DB.set('users',us);PAGES.profile();toast('Perfil atualizado.')});
$('#pm')&&($('#pm').onclick=()=>{/* BACKEND: pagamento/subscrição (ex.: Stripe) */const us=DB.get('users');us.find(x=>x.id===u.id).plan=u.plan==='premium'?'cancelled':'premium';DB.set('users',us);PAGES.profile();toast('Plano atualizado (simulação).')})};
PAGES.settings=()=>{const u=me(),s=DB.get('settings',{notify:true,goalH:10});C().innerHTML=`<div class="ph"><h1>Definições</h1></div><div class="two"><div class="card"><h3>Preferências</h3><label>Tema<select id="th"><option value="dark">Preto e dourado</option><option value="light">Claro</option></select></label><label><input type="checkbox" id="nt" ${s.notify!==false?'checked':''}>Notificações de lembretes</label><label>Meta semanal de estudo (horas)<input id="gh" type="number" min="1" value="${s.goalH||10}"></label><button class="btn p" id="sv">Guardar</button></div>
<div class="card"><h3>Segurança</h3><form id="pf" novalidate>${pwField('po','Palavra-passe atual')}${pwField('pn','Nova palavra-passe')}<p class="err" role="alert"></p><button class="btn p">Alterar palavra-passe</button></form></div></div><div class="card"><h3>Zona de perigo</h3><button class="btn d" id="dl">Eliminar conta</button></div>`;eyes();$('#th').value=localStorage.getItem('sf_theme')||'dark';
$('#sv').onclick=()=>{localStorage.setItem('sf_theme',$('#th').value);document.documentElement.dataset.theme=$('#th').value;DB.set('settings',{notify:$('#nt').checked,goalH:+$('#gh').value||10});toast('Preferências guardadas.')};
$('#pf').onsubmit=e=>{e.preventDefault();const us=DB.get('users'),x=us.find(a=>a.id===u.id);if(hash($('#po').value)!==x.pass)return $('.err').textContent='Palavra-passe atual incorreta.';if($('#pn').value.length<6)return $('.err').textContent='Mínimo 6 caracteres.';x.pass=hash($('#pn').value);DB.set('users',us);e.target.reset();$('.err').textContent='';toast('Palavra-passe alterada.')};
$('#dl').onclick=()=>{if(!confirm('Eliminar a conta e todos os dados? Esta ação é irreversível.'))return;DB.set('users',DB.get('users').filter(x=>x.id!==u.id));Object.keys(localStorage).filter(k=>k.startsWith('sf_'+u.id+'_')).forEach(k=>localStorage.removeItem(k));localStorage.removeItem('sf_currentUser');location.href='index.html'}};
/* ---------- Administração ---------- */
PAGES.admin=()=>{const us=DB.get('users'),ex=sum(DB.get('expenses'),'amount'),r=rev(),M=months();C().innerHTML=`<div class="ph"><h1>Visão geral</h1></div><div class="stats">${st(us.length,'Utilizadores totais')+st(us.filter(u=>!u.blocked).length,'Ativos')+st(us.filter(u=>u.created>new Date(Date.now()-30*864e5).toISOString()).length,'Novos (30 dias)')+st(us.filter(u=>u.plan==='premium').length,'Subscrições')+st(eur(r),'Receita mensal')+st(eur(ex),'Despesas')+st(eur(r-ex),'Lucro estimado')}</div>
<div class="two"><div class="card"><h3>Crescimento de utilizadores</h3>${bars(M.map(m=>m.l),M.map(m=>us.filter(u=>u.created<m.e).length))}</div><div class="card"><h3>Receita (€/mês)</h3>${bars(M.map(m=>m.l),M.map(m=>us.filter(u=>u.plan==='premium'&&u.created<m.e).length*24))}</div></div>`};
PAGES['admin-users']=()=>{const q={};C().innerHTML=`<div class="ph"><h1>Utilizadores</h1></div><div class="row"><input id="sq" placeholder="Pesquisar nome ou e-mail" aria-label="Pesquisar"><select id="fp" aria-label="Tipo"><option value="">Todos os tipos</option>${Object.entries(pl).map(e=>`<option value="${e[0]}">${e[1]}</option>`).join('')}</select><select id="fs" aria-label="Estado"><option value="">Qualquer estado</option><option value="a">Ativos</option><option value="b">Bloqueados</option></select></div><div class="card tw" style="margin-top:14px"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Registo</th><th>Tipo</th><th>Estado</th><th></th></tr></thead><tbody id="tb"></tbody></table></div>`;
const draw=()=>{const s=$('#sq').value.toLowerCase(),p=$('#fp').value,z=$('#fs').value;$('#tb').innerHTML=DB.get('users').filter(u=>(u.name+u.email).toLowerCase().includes(s)&&(!p||u.plan===p)&&(!z||(z==='b')===u.blocked)).map(u=>`<tr data-id="${u.id}"><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${fd(u.created.slice(0,10))}</td><td>${pl[u.plan]}</td><td>${u.blocked?'Bloqueado':'Ativo'}</td><td><button class="btn sm" data-a="v">Detalhes</button> ${u.role==='admin'?'':`<button class="btn sm d" data-a="b">${u.blocked?'Desbloquear':'Bloquear'}</button>`}</td></tr>`).join('')};
['sq','fp','fs'].forEach(i=>$('#'+i).oninput=draw);$('#tb').onclick=e=>{const b=e.target.closest('[data-a]');if(!b)return;const us=DB.get('users'),u=us.find(x=>x.id===b.closest('tr').dataset.id);if(b.dataset.a==='b'){u.blocked=!u.blocked;DB.set('users',us);draw()}else modal(`<h2 class="gold">${esc(u.name)}</h2><p>${esc(u.email)}<br>Tipo: ${pl[u.plan]}<br>Registo: ${fd(u.created.slice(0,10))}<br>Estado: ${u.blocked?'Bloqueado':'Ativo'}</p>`)};draw()};
PAGES['admin-ai']=()=>crud({key:'aiContent',title:'Conteúdos IA',newLabel:'Novo conteúdo',fields:[{n:'title',l:'Título',req:1},{n:'type',l:'Tipo',t:'select',opts:['Resumo','Exercício','Quiz','Dica de estudo']},{n:'status',l:'Estado',t:'select',opts:['Rascunho','Publicado']},{n:'body',l:'Conteúdo',t:'textarea'}],
stats:a=>st(5320,'Pedidos à IA (simulado)')+st(a.length,'Conteúdos criados')+st(a.filter(x=>x.status==='Publicado').length,'Publicados')+st(eur(5320*.0021),'Custo estimado'),/* BACKEND: métricas reais da API de IA */
row:i=>`<b>${esc(i.title)}</b> <span class="badge">${esc(i.type)}</span> <span class="badge">${esc(i.status)}</span><br><small>${esc((i.body||'').slice(0,100))}</small>`});
PAGES['admin-finance']=()=>{const us=DB.get('users'),pr=us.filter(u=>u.plan==='premium'),r=rev(),M=months();C().innerHTML=`<div class="ph"><h1>Finanças</h1></div><div class="stats">${st(eur(r),'Receita mensal')+st(eur(r*12),'Receita anual (projeção)')+st(pr.length,'Subscrições ativas')+st(us.filter(u=>u.plan==='cancelled').length,'Cancelamentos')}</div>
<div class="card"><h3>Receita por mês (€)</h3>${bars(M.map(m=>m.l),M.map(m=>us.filter(u=>u.plan==='premium'&&u.created<m.e).length*24))}</div><div class="card tw" style="margin-top:16px"><h3>Pagamentos recentes (simulados)</h3><table><tr><th>Utilizador</th><th>Valor</th><th>Data</th></tr>${pr.map(u=>`<tr><td>${esc(u.name)}</td><td>${eur(24)}</td><td>${fd(u.created.slice(0,10))}</td></tr>`).join('')||'<tr><td colspan="3">Sem pagamentos.</td></tr>'}</table></div>`};
PAGES['admin-expenses']=()=>crud({key:'expenses',title:'Despesas',newLabel:'Nova despesa',fields:[{n:'name',l:'Despesa',req:1},{n:'category',l:'Categoria',t:'select',opts:['Servidores','IA','Marketing','Software','Outros']},{n:'amount',l:'Valor (€)',t:'number',min:0,step:'0.01',req:1},{n:'date',l:'Data',t:'date',def:today(),req:1},{n:'desc',l:'Descrição',t:'textarea'}],
stats:a=>{const t=sum(a,'amount');return st(eur(t),'Total de despesas')+st(eur(rev()),'Receita mensal')+st(eur(rev()-t),'Resultado estimado')},
row:e=>`<b>${esc(e.name)}</b> <span class="badge">${esc(e.category)}</span> ${eur(+e.amount)}<br><small>${fd(e.date)} · ${esc(e.desc||'')}</small>`});
